/*
 * Generate Snappy-framed gossip fixtures from raw SSZ input.
 *
 * This tool wraps raw SSZ bytes into Snappy framed format for gossip fixtures.
 * It does NOT decode/re-encode through Lantern's internal structures, allowing
 * fixtures generated by leanSpec (which may have different signature sizes
 * during the SSZ serialization transition) to be used directly.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "lantern/encoding/snappy.h"

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *fp = fopen(path, "rb");
    if (!fp) {
        fprintf(stderr, "failed to open %s\n", path);
        return NULL;
    }
    if (fseek(fp, 0, SEEK_END) != 0) {
        fclose(fp);
        return NULL;
    }
    long len = ftell(fp);
    if (len < 0) {
        fclose(fp);
        return NULL;
    }
    if (fseek(fp, 0, SEEK_SET) != 0) {
        fclose(fp);
        return NULL;
    }
    uint8_t *buffer = (uint8_t *)malloc((size_t)len);
    if (!buffer) {
        fclose(fp);
        return NULL;
    }
    size_t read = fread(buffer, 1, (size_t)len, fp);
    fclose(fp);
    if (read != (size_t)len) {
        free(buffer);
        return NULL;
    }
    if (out_len) {
        *out_len = (size_t)len;
    }
    return buffer;
}

static int write_file(const char *path, const uint8_t *data, size_t len) {
    FILE *fp = fopen(path, "wb");
    if (!fp) {
        fprintf(stderr, "failed to open %s for writing\n", path);
        return -1;
    }
    size_t written = fwrite(data, 1, len, fp);
    fclose(fp);
    return written == len ? 0 : -1;
}

/*
 * Encode raw SSZ bytes into raw Snappy format (no framing).
 * This matches the gossip protocol encoding used by Lantern.
 */
static int encode_raw_snappy(const char *input_path, const char *output_path) {
    size_t len = 0;
    uint8_t *data = read_file(input_path, &len);
    if (!data) {
        return -1;
    }
    size_t max_compressed = 0;
    if (lantern_snappy_max_compressed_size_raw(len, &max_compressed) != LANTERN_SNAPPY_OK) {
        free(data);
        return -1;
    }
    uint8_t *snappy = (uint8_t *)malloc(max_compressed);
    if (!snappy) {
        free(data);
        return -1;
    }
    size_t snappy_len = 0;
    int encode_rc = lantern_snappy_compress_raw(data, len, snappy, max_compressed, &snappy_len);
    free(data);
    if (encode_rc != LANTERN_SNAPPY_OK) {
        free(snappy);
        fprintf(stderr, "failed to encode raw snappy (rc=%d)\n", encode_rc);
        return -1;
    }
    int write_rc = write_file(output_path, snappy, snappy_len);
    free(snappy);
    return write_rc;
}

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "usage: %s vote|block input.ssz output.snappy\n", argv[0]);
        return 1;
    }
    const char *kind = argv[1];
    const char *input_path = argv[2];
    const char *output_path = argv[3];
    int rc = -1;
    /* Both vote and block use the same raw snappy encoding now.
     * We keep the kind argument for compatibility with the Python script. */
    if (strcmp(kind, "vote") == 0 || strcmp(kind, "block") == 0) {
        rc = encode_raw_snappy(input_path, output_path);
    } else {
        fprintf(stderr, "unknown kind: %s\n", kind);
        return 1;
    }
    return rc == 0 ? 0 : 1;
}
